### PR TITLE
Add logos of organizational members to front page

### LINKED ISSUE #92: Add logos of organizational members
https://modelica.org/association/

This list of organizational members is powerful and we can be proud of it.  We should display this widespread support way more prominently

### PR DESCRIPTION
**Pull request by t-sommer**
fixes #92

### CODE REVIEW

**Comment by t-sommer** [comment]
This is what the logos look like:

image

**Comment by chrbertsch** [comment]
The logos look good, but the selection gives a wrong impression, which companies and organisations are active in the MA. I would display the logos of all organisational members (with smaller size)

**Comment by dzimmer** [comment]
Christian has a point. 
However many small logos may fail to have the desired impact. I have seen pages that solve this problem by swapping the logos with a low frequency...  In this way, all logos remain large and we could start with some big names.  I have no idea how much implementation effort that would be.

**Comment by dzimmer** [comment]
I would suggest a slight rephrasing:

"supported by:"
Logos
"and 21 more organizational members"

(hence it is about the prominence of support and not whether the partner is active or not)
Agreement from me. Go ahead!

**Pull request merged**
