### PR TITLE
restructuring books

### PR DESCRIPTION
**Pull request by dzimmer**
- restructured book page. 
  - General english intros first
  - Non-English second
  - Particular topics last
- removed redundancy
- replaced dead links
- removed inaccessible books
- many minor changes

still todo:
- get better pics of book
- solve layout issues

### CODE REVIEW

**Comment by dzimmer** [comment]
- Layout is now ok on web browser but awfull on Smartphone. I guess this would require some css coding
- There is an open issue with the OMWebbook. Linlöping is trying to fix this

**Comment by dzimmer** [comment]
Ok. Checked again. Layout on mobile seems to be not worse than before. Removing draft status...

**Comment by dzimmer** [comment]
adresses #44

**Review by HansOlsson — APPROVED** [review]
Clearly an improvement.
For the future we might see if we should split non-English literature according to language and how to handle domain-specific ones.

**Pull request merged**
